---
title: Data Extraction
format:
  html:
    toc: true
    number-sections: true
    embed-resources: true 
---

In [32]:
#import dblp
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import lxml
import os
import matplotlib.pyplot as plt
#from dblp_parser import DBLP

In [2]:
os.getcwd()

'/Users/raunakadvani/Desktop/2023-2024/Summer/ANLY645/Project'

In [12]:
output_articles = pd.read_csv('./data/dblp-to-csv/output_inproceedings.csv', delimiter = ';', header = None)

In [13]:
output_articles.head(10)

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,3445422,Arnon Rosenthal,NaN,NaN,SWEE,NaN,NaN,NaN,conf/swee/1998,NaN,...,NaN,NaN,NaN,NaN,The Future of Classic Data Administration: Obj...,NaN,NaN,db/conf/swee/swee1998.html,NaN,1998
1,3445424,Qiming Chen|Umeshwar Dayal,NaN,NaN,CoopIS,NaN,...|...|...|books/mk/GrayR93|books/mk/elmagarm...,NaN,conf/coopis/2000,NaN,...,311-322,NaN,NaN,NaN,Multi-Agent Cooperative Transactions for E-Com...,NaN,NaN,db/conf/coopis/coopis2000.html#ChenD00,NaN,2000
2,3445425,Emmanuel Cecchet|Renaud Lachaize|Takoua Abdell...,NaN,NaN,CoopIS/DOA/ODBASE (2),NaN,NaN,NaN,conf/coopis/2004-2,NaN,...,1571-1589,NaN,NaN,NaN,Evaluation of a Group Communication Middleware...,NaN,NaN,db/conf/coopis/coopis2004-2.html#AbdellatifCL04,NaN,2004
3,3445426,Robert Grob|Stefanie Kethers|Stephan Jacobs,NaN,NaN,CoopIS,NaN,NaN,NaN,conf/coopis/1994,NaN,...,134-145,NaN,NaN,NaN,Towards CIS in Quality Management - Integratio...,NaN,NaN,db/conf/coopis/coopis94.html#GrobJK94,NaN,1994
4,3445427,Evaggelia Pitoura|George Samaras|Panos K. Chry...,NaN,NaN,CoopIS,NaN,...|...|...|...|...|...|...|...|...|...|...|.....,NaN,conf/coopis/2000,NaN,...,102-113,NaN,NaN,NaN,An Evaluation of the Java-Based Approaches to ...,NaN,NaN,db/conf/coopis/coopis2000.html#PapastavrouCSP00,NaN,2000
5,3445428,Arne Koschel|Günter von Bültzingsloewen|Ralf K...,NaN,NaN,CoopIS,COOPIS1997/79460230.pdf,NaN,NaN,conf/coopis/97,NaN,...,230,NaN,NaN,NaN,Poster on Accept Heterogeneity: An Event Monit...,NaN,NaN,db/conf/coopis/coopis97.html#BultzingsloewenKK97,NaN,1997
6,3445429,Enrico Giacoletto|Karl Aberer,NaN,NaN,OTM,NaN,NaN,NaN,conf/coopis/2003,NaN,...,785-802,NaN,NaN,NaN,Automatic Expansion of Manual Email Classifica...,NaN,NaN,db/conf/coopis/coopis2003.html#GiacolettoA03,NaN,2003
7,3445430,Francesco Buccafurri|Gianluca Lax,NaN,NaN,CoopIS/DOA/ODBASE (1),NaN,NaN,NaN,conf/coopis/2004-1,NaN,...,563-580,NaN,NaN,NaN,TLS: A Tree-Based DHT Lookup Service for Highl...,NaN,NaN,db/conf/coopis/coopis2004-1.html#BuccafurriL04,NaN,2004
8,3445431,Ling Liu|Ling-Ling Yan|M. Tamer Özsu,NaN,NaN,CoopIS,COOPIS1997/79460130.pdf,NaN,NaN,conf/coopis/97,NaN,...,130-139,NaN,NaN,NaN,Accessing Heterogeneous Data Through Homogeniz...,NaN,NaN,db/conf/coopis/coopis97.html#YanOL97,NaN,1997
9,3445432,Michele Amoretti|Monica Reggiani|Stefano Botta...,NaN,NaN,OTM,NaN,NaN,NaN,conf/coopis/2003,NaN,...,1063-1080,NaN,NaN,NaN,Designing Telerobotic Systems as Distributed C...,NaN,NaN,db/conf/coopis/coopis2003.html#AmorettiBRC03,NaN,2003

In [15]:
output_articles.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
           dtype='int64')

In [16]:
output_articles = output_articles[[1, 24]]

In [17]:
output_articles.head(10)

,1,24
0,Arnon Rosenthal,The Future of Classic Data Administration: Obj...
1,Qiming Chen|Umeshwar Dayal,Multi-Agent Cooperative Transactions for E-Com...
2,Emmanuel Cecchet|Renaud Lachaize|Takoua Abdell...,Evaluation of a Group Communication Middleware...
3,Robert Grob|Stefanie Kethers|Stephan Jacobs,Towards CIS in Quality Management - Integratio...
4,Evaggelia Pitoura|George Samaras|Panos K. Chry...,An Evaluation of the Java-Based Approaches to ...
5,Arne Koschel|Günter von Bültzingsloewen|Ralf K...,Poster on Accept Heterogeneity: An Event Monit...
6,Enrico Giacoletto|Karl Aberer,Automatic Expansion of Manual Email Classifica...
7,Francesco Buccafurri|Gianluca Lax,TLS: A Tree-Based DHT Lookup Service for Highl...
8,Ling Liu|Ling-Ling Yan|M. Tamer Özsu,Accessing Heterogeneous Data Through Homogeniz...
9,Michele Amoretti|Monica Reggiani|Stefano Botta...,Designing Telerobotic Systems as Distributed C...

In [18]:
output_articles.columns

Int64Index([1, 24], dtype='int64')

In [21]:
output_articles = output_articles.rename(columns = {1: "authors", 24: "paper"})

In [22]:
output_articles.head()

,authors,paper
0,Arnon Rosenthal,The Future of Classic Data Administration: Obj...
1,Qiming Chen|Umeshwar Dayal,Multi-Agent Cooperative Transactions for E-Com...
2,Emmanuel Cecchet|Renaud Lachaize|Takoua Abdell...,Evaluation of a Group Communication Middleware...
3,Robert Grob|Stefanie Kethers|Stephan Jacobs,Towards CIS in Quality Management - Integratio...
4,Evaggelia Pitoura|George Samaras|Panos K. Chry...,An Evaluation of the Java-Based Approaches to ...

In [28]:
output_articles = output_articles.dropna(subset=['authors', 'paper'], how='any')

In [29]:
output_articles['authors'] = output_articles['authors'].apply(lambda x: x.split('|'))
output_articles = output_articles[output_articles['authors'].apply(len) > 1]

In [30]:
output_articles.head()

,authors,paper
1,"[Qiming Chen, Umeshwar Dayal]",Multi-Agent Cooperative Transactions for E-Com...
2,"[Emmanuel Cecchet, Renaud Lachaize, Takoua Abd...",Evaluation of a Group Communication Middleware...
3,"[Robert Grob, Stefanie Kethers, Stephan Jacobs]",Towards CIS in Quality Management - Integratio...
4,"[Evaggelia Pitoura, George Samaras, Panos K. C...",An Evaluation of the Java-Based Approaches to ...
5,"[Arne Koschel, Günter von Bültzingsloewen, Ral...",Poster on Accept Heterogeneity: An Event Monit...

In [40]:
output_articles['num_authors'] = output_articles['authors'].apply(len)

In [51]:
output_articles.to_csv("./data/clean/output_articles.csv")

In [54]:
papers = pd.read_csv('./data/dblp-to-csv/output_book.csv', delimiter = ';', header = None)

In [57]:
papers.head()

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,5551,Alberto Maria Metelli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Polytechnic University of Milan, Italy",Frontiers in Artificial Intelligence and Appli...,db/series/faia/index.html,NaN,NaN,Exploiting environment configurability in rein...,NaN,361,2022
1,7591,Markus Aleksy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Tokyo Denki University, Japan",NaN,NaN,NaN,NaN,Realizing the leasing concept in distributed s...,NaN,NaN,2007
2,9823,Michael A. Curth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Planspieltechnik und Computer-based-Training z...,NaN,NaN,1989
3,9861,Eberhard E. Wedekind,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Informationsmanagement in der Organisationspla...,NaN,NaN,1988
4,10058,Peter F. Tropschuh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Rechnerunterstützung für das Projektieren mit ...,NaN,NaN,1989

In [58]:
papers = papers[[1, 30]]

In [59]:
papers = papers.rename(columns = {1: "authors", 30: "paper"})
papers = papers.dropna(subset=['authors', 'paper'], how='any')
papers['authors'] = papers['authors'].apply(lambda x: x.split('|'))
papers = papers[papers['authors'].apply(len) > 1]

In [61]:
papers.to_csv('./data/clean/papers.csv')

In [63]:
data = pd.read_csv('./data/dblp-to-csv/output_data.csv', header = None, delimiter = ';')

In [64]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0,Peggy Joy Lu,0000-0001-9742-4173,NaN,https://doi.org/10.21227/0ndm-6g50,NaN,data/10/Lu22c,2023-03-15,May,NaN,...,IEEE DataPort,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MI3.,2022.0
1,1,Ivan Homoliak|Petr Hanácek,0000-0001-5507-0768|0000-0002-0790-0875,NaN,https://doi.org/10.21227/081t-dj23,oa,data/10/HomoliakH22,2023-03-15,May,NaN,...,IEEE DataPort,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ASNM Datasets: A Collection of Network Traffic...,2022.0
2,2,Hyung-Jong Kim|TaeYoung Kim,0000-0001-7505-7931|0000-0002-0608-5397,NaN,https://doi.org/10.21227/b7mg-yb75,NaN,data/10/KimK22,2023-03-15,January,NaN,...,IEEE DataPort,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Experimental dataset for the Performance Evalu...,2022.0
3,3,Simone Godio,NaN,NaN,https://doi.org/10.21227/10av-kj18,NaN,data/10/Godio21,2023-03-15,April,NaN,...,IEEE DataPort,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Visual Inertial Odometry Sensor Fusion Approac...,2021.0
4,4,R. Bock,NaN,NaN,https://doi.org/10.24432/C52C8B,NaN,data/10/Bock07,2023-07-17,April,NaN,...,UC Irvine Machine Learning Repository,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MAGIC Gamma Telescope.,2007.0

In [65]:
data = data[[1,19]]
data = data.rename(columns = {1: "authors", 19: "paper"})
data = data.dropna(subset=['authors', 'paper'], how='any')
data['authors'] = data['authors'].apply(lambda x: x.split('|'))
data = data[data['authors'].apply(len) > 1]

In [66]:
data.to_csv('./data/clean/data.csv')

In [68]:
incollection = pd.read_csv('./data/dblp-to-csv/output_incollection.csv', header = None, delimiter = ';')

In [69]:
incollection.head()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,116542,Lynne Parker,NaN,Handbook of Computational Intelligence,NaN,NaN,NaN,NaN,reference/sp/2015ci,https://doi.org/10.1007/978-3-662-43505-2_72,...,NaN,1395-1406,NaN,NaN,NaN,NaN,NaN,Collective Manipulation and Construction.,db/reference/sp/ci2015.html#Parker15,2015
1,116543,Oscar Montiel Ross|Roberto Sepúlveda Cruz,0000-0002-7060-9204,Handbook of Computational Intelligence,NaN,NaN,NaN,NaN,reference/sp/2015ci,https://doi.org/10.1007/978-3-662-43505-2_76,...,NaN,1451-1477,NaN,NaN,NaN,NaN,NaN,Evolving Embedded Fuzzy Controllers.,db/reference/sp/ci2015.html#RossC15,2015
2,116544,Ravi Jhawar|Vincenzo Piuri,NaN,Handbook on Data Centers,NaN,NaN,NaN,NaN,reference/sp/2015dc,https://doi.org/10.1007/978-1-4939-2092-1_45,...,NaN,1285-1305,NaN,NaN,encyclopedia,NaN,NaN,Dependability-Oriented Resource Management Sch...,db/reference/sp/dc2015.html#JhawarP15,2015
3,116545,Anna Monreale|Dino Pedreschi|Francesca Pratesi,0000-0003-4801-3225,Handbook of Mobile Data Privacy,NaN,NaN,NaN,NaN,reference/sp/2018mdp,https://doi.org/10.1007/978-3-319-98161-1_10,...,NaN,253-277,NaN,NaN,encyclopedia,NaN,NaN,Privacy by Design for Mobility Data Analytics.,db/reference/sp/mdp2018.html#PratesiMP18,2018
4,116546,Evgenia Smirni|Lydia Y. Chen|Robert Birke,NaN,Handbook on Data Centers,NaN,NaN,NaN,NaN,reference/sp/2015dc,https://doi.org/10.1007/978-1-4939-2092-1_43,...,NaN,1257-1266,NaN,NaN,encyclopedia,NaN,NaN,Usage Patterns in Multi-tenant Data Centers: a...,db/reference/sp/dc2015.html#BirkeCS15,2015

In [70]:
incollection = incollection[[1,22]]
incollection = incollection.rename(columns = {1: "authors", 22: "paper"})
incollection = incollection.dropna(subset=['authors', 'paper'], how='any')
incollection['authors'] = incollection['authors'].apply(lambda x: x.split('|'))
incollection = incollection[incollection['authors'].apply(len) > 1]

In [72]:
incollection.to_csv('./data/clean/incollection.csv')

In [87]:
inproceedings = pd.read_csv('./data/dblp-to-csv/output_inproceedings.csv', header = None, delimiter = ';')

In [88]:
inproceedings.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,3445422,Arnon Rosenthal,NaN,NaN,SWEE,NaN,NaN,NaN,conf/swee/1998,NaN,...,NaN,NaN,NaN,NaN,The Future of Classic Data Administration: Obj...,NaN,NaN,db/conf/swee/swee1998.html,NaN,1998
1,3445424,Qiming Chen|Umeshwar Dayal,NaN,NaN,CoopIS,NaN,...|...|...|books/mk/GrayR93|books/mk/elmagarm...,NaN,conf/coopis/2000,NaN,...,311-322,NaN,NaN,NaN,Multi-Agent Cooperative Transactions for E-Com...,NaN,NaN,db/conf/coopis/coopis2000.html#ChenD00,NaN,2000
2,3445425,Emmanuel Cecchet|Renaud Lachaize|Takoua Abdell...,NaN,NaN,CoopIS/DOA/ODBASE (2),NaN,NaN,NaN,conf/coopis/2004-2,NaN,...,1571-1589,NaN,NaN,NaN,Evaluation of a Group Communication Middleware...,NaN,NaN,db/conf/coopis/coopis2004-2.html#AbdellatifCL04,NaN,2004
3,3445426,Robert Grob|Stefanie Kethers|Stephan Jacobs,NaN,NaN,CoopIS,NaN,NaN,NaN,conf/coopis/1994,NaN,...,134-145,NaN,NaN,NaN,Towards CIS in Quality Management - Integratio...,NaN,NaN,db/conf/coopis/coopis94.html#GrobJK94,NaN,1994
4,3445427,Evaggelia Pitoura|George Samaras|Panos K. Chry...,NaN,NaN,CoopIS,NaN,...|...|...|...|...|...|...|...|...|...|...|.....,NaN,conf/coopis/2000,NaN,...,102-113,NaN,NaN,NaN,An Evaluation of the Java-Based Approaches to ...,NaN,NaN,db/conf/coopis/coopis2000.html#PapastavrouCSP00,NaN,2000

In [89]:
inproceedings = inproceedings[[1,24]]
inproceedings = inproceedings.rename(columns = {1: "authors", 24: "paper"})
inproceedings = inproceedings.dropna(subset=['authors', 'paper'], how='any')
inproceedings['authors'] = inproceedings['authors'].apply(lambda x: x.split('|'))
inproceedings = inproceedings[inproceedings['authors'].apply(len) > 1]

In [90]:
inproceedings.to_csv('./data/clean/inproceedings.csv')

In [92]:
proceedings = pd.read_csv('./data/dblp-to-csv/output_proceedings.csv', header = None, delimiter = ';')

In [93]:
proceedings.head()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,124985,NaN,NaN,NaN,NaN,NaN,Amir Hossein Alavi|Amir Hossein Gandomi|Conor ...,0000-0002-2798-0104|0000-0002-7002-5815|0000-0...,https://doi.org/10.1007/978-3-319-20883-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Handbook of Genetic Programming Applications,db/reference/genetic/genetic2015.html,NaN,2015
1,143933,NaN,NaN,NaN,NaN,NaN,Ankur Agarwal|Borko Furht,NaN,https://doi.org/10.1007/978-1-4614-8495-0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Handbook of Medical and Healthcare Technologies,db/reference/med/med2013.html,NaN,2013
2,3445443,NaN,NaN,OTM,NaN,NaN,Douglas C. Schmidt|Robert Meersman|Zahir Tari,NaN,https://doi.org/10.1007/b94348,NaN,...,NaN,NaN,Lecture Notes in Computer Science,db/series/lncs/index.html,NaN,NaN,On The Move to Meaningful Internet Systems 200...,db/conf/coopis/coopis2003.html,2888,2003
3,3445549,NaN,NaN,CoopIS/DOA/ODBASE,NaN,NaN,Robert Meersman|Zahir Tari,NaN,https://doi.org/10.1007/b102176,NaN,...,NaN,NaN,Lecture Notes in Computer Science,db/series/lncs/index.html,NaN,NaN,On the Move to Meaningful Internet Systems 200...,db/conf/coopis/coopis2004-2.html,3291,2004
4,3445571,NaN,NaN,CoopIS,NaN,NaN,Carlo Batini|Fausto Giunchiglia|Massimo Mecell...,NaN,https://doi.org/10.1007/3-540-44751-2,NaN,...,NaN,NaN,Lecture Notes in Computer Science,db/series/lncs/index.html,NaN,NaN,"Cooperative Information Systems, 9th Internati...",db/conf/coopis/coopis2001.html,2172,2001

In [94]:
proceedings = proceedings[[6,28]]
proceedings = proceedings.rename(columns = {6: "authors", 28: "paper"})
proceedings = proceedings.dropna(subset=['authors', 'paper'], how='any')
proceedings['authors'] = proceedings['authors'].apply(lambda x: x.split('|'))
proceedings = proceedings[proceedings['authors'].apply(len) > 1]

In [95]:
proceedings.head()

,authors,paper
0,"[Amir Hossein Alavi, Amir Hossein Gandomi, Con...",Handbook of Genetic Programming Applications
1,"[Ankur Agarwal, Borko Furht]",Handbook of Medical and Healthcare Technologies
2,"[Douglas C. Schmidt, Robert Meersman, Zahir Tari]",On The Move to Meaningful Internet Systems 200...
3,"[Robert Meersman, Zahir Tari]",On the Move to Meaningful Internet Systems 200...
4,"[Carlo Batini, Fausto Giunchiglia, Massimo Mec...","Cooperative Information Systems, 9th Internati..."

In [96]:
proceedings.to_csv('./data/clean/proceedings.csv')

In [98]:
data_frames = []
folder_path = './data/clean'
csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]

for file in csv_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path)
    data_frames.append(df)

combined_df = pd.concat(data_frames, ignore_index = True)

combined_df.drop_duplicates(subset = ['authors', 'paper'], inplace=True)

In [100]:
combined_df.to_csv('./data/clean/combined.csv')